### ISSUE TITLE
slurm 21.08.2 compatibility

### ISSUE THREAD

**Issue by jhl667** [natefoo/slurm-drmaa#66]
Hi, just wanted to note this here.  Following error during compilation:

libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I//include -I../drmaa_utils/ -Wno-long-long -D_REENTRANT -D_THREAD_SAFE -DNDEBUG -D_GNU_SOURCE -DCONFDIR=/etc -Wall -W -Wno-unused-parameter -Wno-format-zero-length -pedantic -std=c99 -g -O0 -pthread -MT libdrmaa_la-job.lo -MD -MP -MF .deps/libdrmaa_la-job.Tpo -c job.c  -fPIC -DPIC -o .libs/libdrmaa_la-job.o
job.c: In function ‘slurmdrmaa_job_control’:
job.c:104:8: error: too few arguments to function ‘slurm_kill_job2’
     if(slurm_kill_job2(self->job_id, SIGKILL, 0) == -1) {
        ^~~~~~~~~~~~~~~
In file included from ../slurm_drmaa/job.h:29,
                 from job.c:31:
/usr/include/slurm/slurm.h:3531:12: note: declared here
 extern int slurm_kill_job2(const char *job_id, uint16_t signal, uint16_t flags,
            ^~~~~~~~~~~~~~~
job.c: In function ‘slurmdrmaa_job_update_status’:
job.c:364:24: warning: this statement may fall through [-Wimplicit-fallthrough=]
      self->exit_status = -1;
      ~~~~~~~~~~~~~~~~~~^~~~
job.c:365:5: note: here
     case JOB_FAILED:
     ^~~~

I added NULL argument to slurm_kill_job2 call and it compiled.

**Comment by kimchitsigai** [comment]
Hi,

I encountered this error when I compiled slurm-drmaa INCLUDEing the header files of a previous version of slurm (20.02). 
By INCLUDEing, I mean that 'configure' generated incorrect compile options.

Best,
Kimchi

**Comment by natefoo** [comment]
slurm-drmaa definitely works with 21.08, this does seem like a mismatch as @kimchitsigai mentioned. Are you still experiencing issues with this?

**Comment by jhl667** [comment]
@natefoo I'm going to close this, we are no longer running in to this type of issue.
